/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as ApiPolishRouteImport } from './routes/api/polish'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiLocalConfigRouteImport } from './routes/api/local-config'
import { Route as ApiGrammarRouteImport } from './routes/api/grammar'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppWorkbenchIdRouteImport } from './routes/app/workbench/$id'
import { Route as AppPreviewTemplateIdRouteImport } from './routes/app/preview-template/$id'
import { Route as AppDashboardTemplatesRouteImport } from './routes/app/dashboard/templates'
import { Route as AppDashboardSettingsRouteImport } from './routes/app/dashboard/settings'
import { Route as AppDashboardResumesRouteImport } from './routes/app/dashboard/resumes'
import { Route as AppDashboardAiRouteImport } from './routes/app/dashboard/ai'
import { Route as ApiProxyImageRouteImport } from './routes/api/proxy/image'
import { Route as ApiAgentUploadRouteImport } from './routes/api/agent/upload'
import { Route as ApiAgentParseRouteImport } from './routes/api/agent/parse'
import { Route as ApiAgentOptimizeRouteImport } from './routes/api/agent/optimize'
import { Route as ApiAgentCoverageRouteImport } from './routes/api/agent/coverage'
import { Route as ApiAgentAutofillRouteImport } from './routes/api/agent/autofill'
import { Route as ApiAgentAtsAuditRouteImport } from './routes/api/agent/ats-audit'
import { Route as ApiAgentAnalyzeJdRouteImport } from './routes/api/agent/analyze-jd'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolishRoute = ApiPolishRouteImport.update({
  id: '/api/polish',
  path: '/api/polish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalConfigRoute = ApiLocalConfigRouteImport.update({
  id: '/api/local-config',
  path: '/api/local-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrammarRoute = ApiGrammarRouteImport.update({
  id: '/api/grammar',
  path: '/api/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppWorkbenchIdRoute = AppWorkbenchIdRouteImport.update({
  id: '/app/workbench/$id',
  path: '/app/workbench/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPreviewTemplateIdRoute = AppPreviewTemplateIdRouteImport.update({
  id: '/app/preview-template/$id',
  path: '/app/preview-template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardTemplatesRoute = AppDashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardResumesRoute = AppDashboardResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAiRoute = AppDashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppDashboardRoute,
} as any)
const ApiProxyImageRoute = ApiProxyImageRouteImport.update({
  id: '/api/proxy/image',
  path: '/api/proxy/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentUploadRoute = ApiAgentUploadRouteImport.update({
  id: '/api/agent/upload',
  path: '/api/agent/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentParseRoute = ApiAgentParseRouteImport.update({
  id: '/api/agent/parse',
  path: '/api/agent/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentOptimizeRoute = ApiAgentOptimizeRouteImport.update({
  id: '/api/agent/optimize',
  path: '/api/agent/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentCoverageRoute = ApiAgentCoverageRouteImport.update({
  id: '/api/agent/coverage',
  path: '/api/agent/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAutofillRoute = ApiAgentAutofillRouteImport.update({
  id: '/api/agent/autofill',
  path: '/api/agent/autofill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAtsAuditRoute = ApiAgentAtsAuditRouteImport.update({
  id: '/api/agent/ats-audit',
  path: '/api/agent/ats-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAnalyzeJdRoute = ApiAgentAnalyzeJdRouteImport.update({
  id: '/api/agent/analyze-jd',
  path: '/api/agent/analyze-jd',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/grammar': typeof ApiGrammarRoute
  '/api/local-config': typeof ApiLocalConfigRoute
  '/api/models': typeof ApiModelsRoute
  '/api/polish': typeof ApiPolishRoute
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/agent/analyze-jd': typeof ApiAgentAnalyzeJdRoute
  '/api/agent/ats-audit': typeof ApiAgentAtsAuditRoute
  '/api/agent/autofill': typeof ApiAgentAutofillRoute
  '/api/agent/coverage': typeof ApiAgentCoverageRoute
  '/api/agent/optimize': typeof ApiAgentOptimizeRoute
  '/api/agent/parse': typeof ApiAgentParseRoute
  '/api/agent/upload': typeof ApiAgentUploadRoute
  '/api/proxy/image': typeof ApiProxyImageRoute
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/preview-template/$id': typeof AppPreviewTemplateIdRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/grammar': typeof ApiGrammarRoute
  '/api/local-config': typeof ApiLocalConfigRoute
  '/api/models': typeof ApiModelsRoute
  '/api/polish': typeof ApiPolishRoute
  '/app': typeof AppIndexRoute
  '/api/agent/analyze-jd': typeof ApiAgentAnalyzeJdRoute
  '/api/agent/ats-audit': typeof ApiAgentAtsAuditRoute
  '/api/agent/autofill': typeof ApiAgentAutofillRoute
  '/api/agent/coverage': typeof ApiAgentCoverageRoute
  '/api/agent/optimize': typeof ApiAgentOptimizeRoute
  '/api/agent/parse': typeof ApiAgentParseRoute
  '/api/agent/upload': typeof ApiAgentUploadRoute
  '/api/proxy/image': typeof ApiProxyImageRoute
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/preview-template/$id': typeof AppPreviewTemplateIdRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/grammar': typeof ApiGrammarRoute
  '/api/local-config': typeof ApiLocalConfigRoute
  '/api/models': typeof ApiModelsRoute
  '/api/polish': typeof ApiPolishRoute
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/agent/analyze-jd': typeof ApiAgentAnalyzeJdRoute
  '/api/agent/ats-audit': typeof ApiAgentAtsAuditRoute
  '/api/agent/autofill': typeof ApiAgentAutofillRoute
  '/api/agent/coverage': typeof ApiAgentCoverageRoute
  '/api/agent/optimize': typeof ApiAgentOptimizeRoute
  '/api/agent/parse': typeof ApiAgentParseRoute
  '/api/agent/upload': typeof ApiAgentUploadRoute
  '/api/proxy/image': typeof ApiProxyImageRoute
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/preview-template/$id': typeof AppPreviewTemplateIdRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/api/grammar'
    | '/api/local-config'
    | '/api/models'
    | '/api/polish'
    | '/app/dashboard'
    | '/app/'
    | '/api/agent/analyze-jd'
    | '/api/agent/ats-audit'
    | '/api/agent/autofill'
    | '/api/agent/coverage'
    | '/api/agent/optimize'
    | '/api/agent/parse'
    | '/api/agent/upload'
    | '/api/proxy/image'
    | '/app/dashboard/ai'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/preview-template/$id'
    | '/app/workbench/$id'
    | '/app/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/api/grammar'
    | '/api/local-config'
    | '/api/models'
    | '/api/polish'
    | '/app'
    | '/api/agent/analyze-jd'
    | '/api/agent/ats-audit'
    | '/api/agent/autofill'
    | '/api/agent/coverage'
    | '/api/agent/optimize'
    | '/api/agent/parse'
    | '/api/agent/upload'
    | '/api/proxy/image'
    | '/app/dashboard/ai'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/preview-template/$id'
    | '/app/workbench/$id'
    | '/app/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/api/grammar'
    | '/api/local-config'
    | '/api/models'
    | '/api/polish'
    | '/app/dashboard'
    | '/app/'
    | '/api/agent/analyze-jd'
    | '/api/agent/ats-audit'
    | '/api/agent/autofill'
    | '/api/agent/coverage'
    | '/api/agent/optimize'
    | '/api/agent/parse'
    | '/api/agent/upload'
    | '/api/proxy/image'
    | '/app/dashboard/ai'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/preview-template/$id'
    | '/app/workbench/$id'
    | '/app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRoute
  ApiGrammarRoute: typeof ApiGrammarRoute
  ApiLocalConfigRoute: typeof ApiLocalConfigRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPolishRoute: typeof ApiPolishRoute
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  ApiAgentAnalyzeJdRoute: typeof ApiAgentAnalyzeJdRoute
  ApiAgentAtsAuditRoute: typeof ApiAgentAtsAuditRoute
  ApiAgentAutofillRoute: typeof ApiAgentAutofillRoute
  ApiAgentCoverageRoute: typeof ApiAgentCoverageRoute
  ApiAgentOptimizeRoute: typeof ApiAgentOptimizeRoute
  ApiAgentParseRoute: typeof ApiAgentParseRoute
  ApiAgentUploadRoute: typeof ApiAgentUploadRoute
  ApiProxyImageRoute: typeof ApiProxyImageRoute
  AppPreviewTemplateIdRoute: typeof AppPreviewTemplateIdRoute
  AppWorkbenchIdRoute: typeof AppWorkbenchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polish': {
      id: '/api/polish'
      path: '/api/polish'
      fullPath: '/api/polish'
      preLoaderRoute: typeof ApiPolishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-config': {
      id: '/api/local-config'
      path: '/api/local-config'
      fullPath: '/api/local-config'
      preLoaderRoute: typeof ApiLocalConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grammar': {
      id: '/api/grammar'
      path: '/api/grammar'
      fullPath: '/api/grammar'
      preLoaderRoute: typeof ApiGrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/workbench/$id': {
      id: '/app/workbench/$id'
      path: '/app/workbench/$id'
      fullPath: '/app/workbench/$id'
      preLoaderRoute: typeof AppWorkbenchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/preview-template/$id': {
      id: '/app/preview-template/$id'
      path: '/app/preview-template/$id'
      fullPath: '/app/preview-template/$id'
      preLoaderRoute: typeof AppPreviewTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard/templates': {
      id: '/app/dashboard/templates'
      path: '/templates'
      fullPath: '/app/dashboard/templates'
      preLoaderRoute: typeof AppDashboardTemplatesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/settings': {
      id: '/app/dashboard/settings'
      path: '/settings'
      fullPath: '/app/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/resumes': {
      id: '/app/dashboard/resumes'
      path: '/resumes'
      fullPath: '/app/dashboard/resumes'
      preLoaderRoute: typeof AppDashboardResumesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/ai': {
      id: '/app/dashboard/ai'
      path: '/ai'
      fullPath: '/app/dashboard/ai'
      preLoaderRoute: typeof AppDashboardAiRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/api/proxy/image': {
      id: '/api/proxy/image'
      path: '/api/proxy/image'
      fullPath: '/api/proxy/image'
      preLoaderRoute: typeof ApiProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/upload': {
      id: '/api/agent/upload'
      path: '/api/agent/upload'
      fullPath: '/api/agent/upload'
      preLoaderRoute: typeof ApiAgentUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/parse': {
      id: '/api/agent/parse'
      path: '/api/agent/parse'
      fullPath: '/api/agent/parse'
      preLoaderRoute: typeof ApiAgentParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/optimize': {
      id: '/api/agent/optimize'
      path: '/api/agent/optimize'
      fullPath: '/api/agent/optimize'
      preLoaderRoute: typeof ApiAgentOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/coverage': {
      id: '/api/agent/coverage'
      path: '/api/agent/coverage'
      fullPath: '/api/agent/coverage'
      preLoaderRoute: typeof ApiAgentCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/autofill': {
      id: '/api/agent/autofill'
      path: '/api/agent/autofill'
      fullPath: '/api/agent/autofill'
      preLoaderRoute: typeof ApiAgentAutofillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/ats-audit': {
      id: '/api/agent/ats-audit'
      path: '/api/agent/ats-audit'
      fullPath: '/api/agent/ats-audit'
      preLoaderRoute: typeof ApiAgentAtsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/analyze-jd': {
      id: '/api/agent/analyze-jd'
      path: '/api/agent/analyze-jd'
      fullPath: '/api/agent/analyze-jd'
      preLoaderRoute: typeof ApiAgentAnalyzeJdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardAiRoute: typeof AppDashboardAiRoute
  AppDashboardResumesRoute: typeof AppDashboardResumesRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardTemplatesRoute: typeof AppDashboardTemplatesRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAiRoute: AppDashboardAiRoute,
  AppDashboardResumesRoute: AppDashboardResumesRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardTemplatesRoute: AppDashboardTemplatesRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRoute,
  ApiGrammarRoute: ApiGrammarRoute,
  ApiLocalConfigRoute: ApiLocalConfigRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiPolishRoute: ApiPolishRoute,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  ApiAgentAnalyzeJdRoute: ApiAgentAnalyzeJdRoute,
  ApiAgentAtsAuditRoute: ApiAgentAtsAuditRoute,
  ApiAgentAutofillRoute: ApiAgentAutofillRoute,
  ApiAgentCoverageRoute: ApiAgentCoverageRoute,
  ApiAgentOptimizeRoute: ApiAgentOptimizeRoute,
  ApiAgentParseRoute: ApiAgentParseRoute,
  ApiAgentUploadRoute: ApiAgentUploadRoute,
  ApiProxyImageRoute: ApiProxyImageRoute,
  AppPreviewTemplateIdRoute: AppPreviewTemplateIdRoute,
  AppWorkbenchIdRoute: AppWorkbenchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
